spring:
  application:
    name: FinalAssignment
  datasource:
    url: jdbc:postgresql://localhost:5432/Final
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
        hbm2ddl:
          auto: create
