spring:
  application:
    name: tasks
  datasource:
    url: jdbc:postgresql://65.21.49.186:5432/nata
    username: postgres
    password: W1ndranner
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
        hbm2ddl:
          auto: create
